# 稀有度出现概率（会在插件内部自动标准化为 0-1 之间）
probability:
  普通: 50.0
  稀有: 25.0
  罕见: 12.0
  史诗: 8.0
  珍品: 4.0
  仙品: 1.0

# 搜索动画单个物品持续时间（单位：tick，Minecraft 每秒 20 tick），最终会在 1~5 秒间随机
search:
  min_seconds: 1
  max_seconds: 5

# 冷却时间（单位：秒）
cooldown: 600

# 设置GUI尺寸，可选 27 或 54
setting-gui-size: 54

# 是否在控制台输出调试信息
debug: false
